### ISSUE TITLE
Add native env_from support for ConfigMap setup

### ISSUE THREAD

**Issue by tellmeY18** [terraform-iaac/terraform-kubernetes-deployment#9]
Right now we can only inject individual env vars or secrets via `env`, `env_secret` or `env_field`, but there’s no way to bulk-load a ConfigMap or Secret into the container’s environment using `envFrom`.

Can we add a new `env_from` parameter (list) so that users can pass:

```hcl
env_from = [
  { config_map_ref = { name = "care-production" } },
  { secret_ref     = { name = "care-production" } },
]
```

and have it render the equivalent of:

```yaml
envFrom:
  - configMapRef:
      name: care-production
  - secretRef:
      name: care-production
```

This would let us consume entire ConfigMaps/Secrets without enumerating every key. Thanks!
